FROM pallid/oscript-web-heroku:dev

COPY src /app

ARG TELEGRAM_BOT_TOKEN

# Ставим зависимости указанные в packagedef
RUN curl -o deb oscript.io/Downloads/latest/deb && dpkg -i deb && cd /app && opm install -l 